### GET todos os clientes
GET https://localhost:7021/api/clientes
Accept: application/json

###

### POST novo cliente
POST https://localhost:7021/api/clientes
Content-Type: application/json

{
  "nome": "João da Silva",
  "dataCadastro": "2025-06-18",
  "endereco": {
    "cep": "01001000",
    "numero": "100",
    "complemento": "Apto 202"
  },
  "contatos": [
    { "tipo": "Email", "texto": "joao@email.com" },
    { "tipo": "Telefone", "texto": "(11) 99999-9999" }
  ]
}

###

### PUT atualizar cliente
PUT https://localhost:7021/api/clientes/1
Content-Type: application/json

{
  "id": 1,
  "nome": "João Atualizado",
  "dataCadastro": "2025-06-18",
  "endereco": {
    "cep": "01001000",
    "numero": "123",
    "complemento": "Casa"
  },
  "contatos": [
    { "tipo": "Email", "texto": "novo@email.com" }
  ]
}

###

### DELETE cliente
DELETE https://localhost:7021/api/clientes/1
